name: Build Single Popular App
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'App Name'
        required: true
        default: 'logseq-db'
      title:
        description: 'App Title'
        required: true
        default: 'Logseq DB'
      name_zh:
        description: 'App Name in Chinese'
        required: true
        default: 'Logseq DB'
      url:
        description: 'App URL'
        required: true
        default: 'https://logseq-db-demo.pages.dev/'
  workflow_call:
    inputs:
      name:
        description: 'App Name'
        type: string
        required: true
        default: 'logseq-db'
      title:
        description: 'App Title'
        required: true
        type: string
        default: 'Logseq DB'
      name_zh:
        description: 'App Name in Chinese'
        required: true
        type: string
        default: 'Logseq DB'
      url:
        description: 'App URL'
        required: true
        type: string
        default: 'https://logseq-db-demo.pages.dev/'

jobs:
  build_single_app:
    name: ${{ inputs.title }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [windows]
        include:
          - build: windows
            os: windows-latest
            rust: stable-x86_64-msvc
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Rust cache restore
        id: cache_store
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Config App
        env:
          NAME: ${{ inputs.name }}
          TITLE: ${{ inputs.title }}
          NAME_ZH: ${{ inputs.name_zh }}
          URL: ${{ inputs.url }}
        run: |
          npm install
          npm run build:config

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm run tauri build -- --target x86_64-pc-windows-msvc
          New-Item -Path "output\windows" -ItemType Directory
          Move-Item -Path "src-tauri\target\x86_64-pc-windows-msvc\release\bundle\msi\*.msi" -Destination "output\windows\${{inputs.title}}_x64.msi"

      - name: Restore Cargo Lock File(Windows Only)
        if: matrix.os == 'windows-latest'
        run: |
          git checkout -- src-tauri/Cargo.lock

      - name: Rust cache store
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Upload For Single Build
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          path: 'output/*/*.*'

      - name: Upload For Release
        # arg info: https://github.com/ncipollo/release-action#release-action
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/') == true
        with:
          allowUpdates: true
          artifacts: 'output/*/*.*'
          token: ${{ secrets.GITHUB_TOKEN }}
